# -----------------------------------------------------
#     DJ-SHELL: REGLAS DE VENTANA EXCLUSIVAS          |
# -----------------------------------------------------


windowrule {
  name = dj-shell-bar
  match:class = ^(Dj-Shell)$

  float = on
  move = 0 0
  size = 100% 30
  pin = on

  # comportamiento e interaccion
  no_initial_focus = on
  no_focus = on
  no_shadow = on
  animation = off
  
}




