#================================================
#               ATAJOS DE TECLADO               |
#================================================

#  tux
$tux = SUPER

#==========================
#   VARIABLES Y SCRIPTS   |
#==========================

$SCRIP = ~/.config/hypr-dj-shell/Scriptsitos

#==============================
#       ATAJOS NORMALES       |
#==============================

bind = $tux, Return, exec, kitty
bind = $tux, Q, killactive, 
bind = $tux, E, exec, thunar
bind = $tux, D, exec, rofi -show drun 
#bind = $tux, exec, pkill rofi || true && rofi -show drun -modi drun, filebrowser,run,window

#=============================
#          PANTALLA          |
#=============================


bind = $tux, SPACE, togglefloating,
#bind = $tux, ATL, SPACE, exec, hyprctl dispatch workspaceopt allfloat

#bind = $tux, SHIFT, Return, exec, $scriptcitos/Dropterminal.sh $term

bind = $tux, F, fullscreen,
#bind = $tux, CTR, F, maximize window, fullscreen, 1
bind = $tux, P, pseudo,
bind = $tux, B, exec, xdg-open "https://"

#============================
#  CARACTERISTICAS EXTRAS   |
#============================

bind = $tux, ALT, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl geoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) } {factor =1}; print factor * 2.0')"

bind = $tux, ALT, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')"


#================================
# TECLAS ESPECIALES / HOT KEYS  |
#  Usa fn para activarlos
#================================

bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.5
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAUTL_AUDIO_SINK@ 5%- -l 1.5
bindl  = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
# Esta chingadera abre la hoja de ayuda con la tecla de rog del teclado↴
bindr  = , XF86Launch, exec, $SCRIP/rofi-help.sh

#=============================
# teclado y rendimiento      |
#     Del F1 a F5            |
#=============================

bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle #f1
bindle = , XF86KbdBrightnessDown, exec, brightnessctl --device="asus::kbd_backlight" set 1- #f2
bindle = , Xf86KbdBrightnessUp,   exec, brightnessctl --device="asus::sbd_backlight" set 1+ #f3
# f4 reservado para auro keyboard
bindl = , XF86Launch4, exec, $HOME/.config/hypr-dj-shell/Scriptsitos/toggle-performance.sh #f5

#=============================
# Brillo Pantala Red Sistema |
#       Del F7 a F12         |
#=============================

bindle = , XF86MonBrightnessDown, exec, brightnessctl set 5%- #f7
bindle = , XF86MonBrightnessUp,   exec, brightnessctl set 5%+ #f8
bindl  = , XF86Display, exec, hyprclt dispatch tweak #f9
bindl  = , XF86TouchpadToggle, exec, $SCRIP/touchpad-toggle.sh #f10
bindl  = , XF86Sleep, exec, systemcl suspend #f11 (suspender)
bindl  = , XF86RFKill, exec, rfkill toggle all #f12 (modo avion)

#=============================
#  Teclas especiales Numpad  |
#       Del 1.. 9 + - / *    |
#=============================
# Mapeo de las teclas para trabajo rapido

bind = $tux , KP_Divide, exec, kitty --class floating-term -e btop # Numpad / abre btop
bind = $tux , KP_Multiply, exec, kitty --class floating-term -e python3 #num *abre python
bind = $tux , KP_Substract, exec, hyprctl dispatch workspace -1 #num -
bind = $tux , KP_Add,       exec, hyprctl dispatch workspace +1 #numpad +

